### ISSUE TITLE
Pinout / Datasheet for peripherals

### ISSUE THREAD

**Issue by bakwc** [WeActTC/MiniSTM32H7xx#19]
Hi! Thank you for your awesome board! I have a question about STM32H750 peripheral pinout. Do you have some documentation / pinout scheme or diagram? I'd like to know what are the LCD / Flash / Camera pins? Could you draw it / write it anywhere?

**Comment by fivdi** [comment]
Perhaps you can find what is needed at https://github.com/WeActTC/MiniSTM32H7xx/tree/master/HDK

**Comment by bakwc** [comment]
Thank you, found it here https://github.com/WeActTC/MiniSTM32H7xx/blob/master/HDK/STM32H7xx%20SchDoc%20V11.pdf
